<?php

namespace ContainerFkAz7DN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6P8ix8oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6P8ix8o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6P8ix8o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'teacher' => ['privates', '.errored..service_locator.6P8ix8o.App\\Entity\\Teacher', NULL, 'Cannot autowire service ".service_locator.6P8ix8o": it references class "App\\Entity\\Teacher" but no such service exists.'],
        ], [
            'teacher' => 'App\\Entity\\Teacher',
        ]);
    }
}
