<?php

namespace ContainerFkAz7DN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeacherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6P8ix8o.App\Entity\Teacher' shared service.
     *
     * @return \App\Entity\Teacher
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6P8ix8o": it references class "App\\Entity\\Teacher" but no such service exists.');
    }
}
