<?php

namespace ContainerFkAz7DN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeacherControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TeacherController' shared autowired service.
     *
     * @return \App\Controller\TeacherController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TeacherController.php';

        $container->services['App\\Controller\\TeacherController'] = $instance = new \App\Controller\TeacherController(($container->privates['App\\Repository\\TeacherRepository'] ?? $container->load('getTeacherRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\TeacherController', $container));

        return $instance;
    }
}
