<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFkAz7DN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFkAz7DN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFkAz7DN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFkAz7DN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFkAz7DN\App_KernelDevDebugContainer([
    'container.build_hash' => 'FkAz7DN',
    'container.build_id' => '05efb0ee',
    'container.build_time' => 1597931565,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFkAz7DN');
