<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'add_student' => [[], ['_controller' => 'App\\Controller\\StudentController::add'], [], [['text', '/students/']], [], []],
    'get_one_student' => [['id'], ['_controller' => 'App\\Controller\\StudentController::getOne'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/students']], [], []],
    'get_all_students' => [[], ['_controller' => 'App\\Controller\\StudentController::getAll'], [], [['text', '/students/']], [], []],
    'update_student' => [['id'], ['_controller' => 'App\\Controller\\StudentController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/students']], [], []],
    'delete_student' => [['id'], ['_controller' => 'App\\Controller\\StudentController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/students']], [], []],
    'add_teacher' => [[], ['_controller' => 'App\\Controller\\TeacherController::add'], [], [['text', '/teachers/']], [], []],
    'get_one_teacher' => [['id'], ['_controller' => 'App\\Controller\\TeacherController::getOne'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/teachers']], [], []],
    'get_all_teachers' => [[], ['_controller' => 'App\\Controller\\TeacherController::getAll'], [], [['text', '/teachers/']], [], []],
    'update_teacher' => [['id'], ['_controller' => 'App\\Controller\\TeacherController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/teachers']], [], []],
    'delete_teacher' => [['id'], ['_controller' => 'App\\Controller\\TeacherController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/teachers']], [], []],
];
